apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    addon.kops.k8s.io/name: karpenter-provisioners.wildlife.io
    app.kubernetes.io/managed-by: kops
    k8s-addon: karpenter-provisioners.wildlife.io
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    kubeReserved:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 150Mi
    systemReserved:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 200Mi
  labels:
    kops.k8s.io/cluster: kops-test.us-east-1.k8s.tfgco.com
    kops.k8s.io/cluster-name: kops-test.us-east-1.k8s.tfgco.com
    kops.k8s.io/instance-group-name: nodes
    kops.k8s.io/instance-group-role: Node
    kops.k8s.io/instancegroup: nodes
    kops.k8s.io/managed-by: kops-controller
  provider:
    launchTemplate: nodes.kops-test.us-east-1.k8s.tfgco.com
    subnetSelector:
      kops.k8s.io/instance-group/nodes: '*'
      kubernetes.io/cluster/kops-test.us-east-1.k8s.tfgco.com: '*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c5.xlarge
    - m5.xlarge
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  startupTaints:
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
