# permissions for end users to view kopscontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kopscontrolplane-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-kops-operator
    app.kubernetes.io/part-of: kubernetes-kops-operator
    app.kubernetes.io/managed-by: kustomize
  name: kopscontrolplane-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kopscontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kopscontrolplanes/status
  verbs:
  - get
