# permissions for end users to view kopsmachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kopsmachinepool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-kops-operator
    app.kubernetes.io/part-of: kubernetes-kops-operator
    app.kubernetes.io/managed-by: kustomize
  name: kopsmachinepool-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kopsmachinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kopsmachinepools/status
  verbs:
  - get
