# This is a patch to remove x-kubernetes-validations from the CRD schema. This is needed because the CRD schema of the NodePool exceeds rule cost estimation when used in a list. The workaround for this is to remove the x-kubernetes-validations from the CRD schema.
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: remove-x-kubernetes-validations
patch: |-
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/properties/evictionHard/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/properties/evictionSoft/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/properties/kubeReserved/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/properties/evictionSoftGracePeriod/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/properties/systemReserved/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/kubelet/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/template/properties/spec/properties/requirements/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePools/items/properties/spec/properties/disruption/properties/budgets/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePoolsV1/items/properties/spec/properties/template/properties/spec/properties/requirements/x-kubernetes-validations
  - op: remove
    path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/karpenterNodePoolsV1/items/properties/spec/properties/disruption/properties/budgets/x-kubernetes-validations
target:
  kind: CustomResourceDefinition
  name: kopsmachinepools.infrastructure.cluster.x-k8s.io