name: Go

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.5

    - name: Run lint
      uses: golangci/golangci-lint-action@v6.1.0
      with:
        version: latest
        args: --timeout 10m0s

  tests:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.5

    - name: Install dependencies
      run: sudo apt install make -y

    - name: Run tests
      run: make test-ci

  docker-image:
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - tests
    - lint

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: tfgco/${{ github.event.repository.name }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          tfgco/${{ github.event.repository.name }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
